### ISSUE TITLE
controller -> loadData function not called

### ISSUE THREAD

**Issue by zopyx** [tabalinas/jsgrid#590] opened 2017-01-17 11:09 UTC
Inside my HTML

https://github.com/zopyx/zopyx.plone.persistentlogger/blob/master/zopyx/plone/persistentlogger/browser/logger.pt#L84-L102

I am initializing my grid with a custom loadData method.

The grid is being initialized however the load_data() method 

https://github.com/zopyx/zopyx.plone.persistentlogger/blob/master/zopyx/plone/persistentlogger/browser/logger.pt#L36-L62

is not called.

(Using jsgrid 1.4.1 with jQuery 1.7.2).

**Comment by zopyx** [comment] 2017-01-17 11:32
![screenshot 2017-01-17 12 31 25](https://cloud.githubusercontent.com/assets/594239/22018819/11ae90fc-dcb1-11e6-8409-3ae61534c5c4.png)

**Comment by tabalinas** [comment] 2017-01-17 12:45
Are you sure `load_data` was not called?
It feels like it was called but since `DATA` is null doing grep on it brings to unexpected results.
I do believe you should use `Promise` which will be returned from the function and resolved with the result of filtering if data already loaded or in `success` of ajax request if not.

**Comment by zopyx** [comment] 2017-01-25 08:24
You are ignoring the JS error that you can see in the screenshot.
Please do not close issues too fast without reading and understanding the problem.

**Comment by zopyx** [comment] 2017-01-25 08:28
In particular the error occurs when you set paging=true.

**Comment by zopyx** [comment] 2017-01-25 08:44
The error persists with jsGrid 1.5.3

**Comment by zopyx** [comment] 2017-01-25 08:46
```
      <script type="text/javascript">

        DATA = null;

        function load_data(filter) {
            
            if (DATA == null) {
                var url = URL + "/@@logger-entries";
                $.ajax({
                    url: url,
                    dataType: 'json',
                    async: false,
                    method: 'GET',
                    success: function(result) {
                        DATA = result;
                    } 
                });
            }

            var result = $.grep(DATA, function(item, idx) {
                for (var key in filter) {
                    var value = filter[key];
                    if (value.length > 0) {
                        if (item[key].indexOf(value) == -1)
                            return false;
                    }
                }
                return true;
            });
            return result;
        }

        function date_renderer(value, row) {
            return row['date_str'];
        }

        function comment_renderer(value, row) {
            var s = value;
            if (row['details']) {
                var details = row['details'];
                s += ' <span class="details"><a class="show-details">[Details]</a><pre class="details-data" style="display: none">' + details + '</pre></span>';                
            }
            return s;
        }

        $(document).ready(function() {

            $('body').on('click', '.show-details', function() {
                $(this).siblings('.details-data').toggle('fast');
            });

            $('.datatable').jsGrid({
                width: "90%",
                height: "600px",
                autoload: true,
                sorting: true,
                paging: true,
                filtering: true,
                pageSize: 16,
                pageButtonCount: 5,
                controller: {
                    loadData: load_data
                },
                fields: [
                    { name: "date", title: "Date", type: "text", width: 30, itemTemplate: date_renderer, autosearch: true},
                    { name: "level", title: "Level", type: "text", width: 20, css: 'field-level'},
                    { name: "username", title: "Username", type: "text", width: 20, css: 'field-username', filtering: true},
                    { name: "comment", title: "Comment", type: "text", css: 'field-comment', filtering: true, itemTemplate: comment_renderer},
                ]
            });
            $('.datatable').jsGrid('loadData');
            
        });
      </script>
```

**Comment by tabalinas** [comment] 2017-01-25 09:09
I'm sorry, but I could not manage to reproduce the bug: https://jsfiddle.net/tabalinas/dhu4zjwn/
Please, feel free to update the fiddle to demonstrate it.

Indeed, I didn't look attentively at the exception posted, because the code itself seemed incorrect to me: I expected ajax call filling `DATA` is async, so `grep` on `DATA` being `null` should fail on the first run. The expected exception seemed obvious, I could not imagine another one

Closing the issue with an answer is a common practice for many support teams. Keeping all the issues opened causes flooding. Once a problem (not necessarily all the problems) is found and we come up with an answer, closing the issue. Absolutely normal is to reopen it once proposed solution doesn't solve the problem. So just feel free to reopen an issue if solution doesn't work.

**Comment by tabalinas** [comment] 2017-01-31 13:57
Cannot reproduce, no answer from the author, closing.

**Closed by tabalinas** 2017-01-31 13:57 UTC
Labels: help wanted

**Comment by zopyx** [comment] 2017-01-31 13:59
Moved on to DataTables due to the broken architecture and implementation.

**Comment by tabalinas** [comment] 2017-01-31 15:09
Could you please be more specific about "broken architecture and implementation"? 
What is exactly meant here?
Thank you very much in advance!
