### ISSUE TITLE
jsGrid.locale not working 

### ISSUE THREAD

**Issue by codingbunny** [tabalinas/jsgrid#207] opened 2016-02-18 04:00 UTC
Hi Tablinas,

Thank you for adding the i18n function. But I have 2 questions: 
1. When I tried to use the jsGrid.locale following the doc, it not working and giving the error: Uncaught TypeError: Cannot read property 'required' of undefined. I was wondering whether I use it right. Here are the fiddles: http://jsfiddle.net/p39kteqh/27/
http://jsfiddle.net/p39kteqh/28/
2. I want to internationalize my header as well, how can I do this? I am wondering if I should use some translate plugins or? 

Thank you very much!

**Comment by tabalinas** [comment] 2016-02-18 08:24
The issue is that the new script `jsgrid.validation.js` was not included in the build.
For temporary fix, you can include it before calling localization function.
The fix will be soon released in v1.4.1.

**Closed** 2016-02-18 08:24 UTC
Labels: bug

**Comment by codingbunny** [comment] 2016-02-19 08:18
Thank you for your reply. It works well.
And what should I do if I want my header to support multi-language?

**Comment by tabalinas** [comment] 2016-02-19 08:22
If you need to localize them just define `title` of the field in the target language.
If you want to support several languages, define a dictionary with the titles, and pick up the title in the grid config according to the current language, like the following:

```js
var titles = { fr: { col1: 'Oui' }, en: { col1: 'Yes'  } };

$('#jsgrid').jsGrid({
    fields: [{ title: titles[currentLang].col1 }]
}); 
```
