### ISSUE TITLE
Having trouble with multiple custom fields of the same type in a single grid

### ISSUE THREAD

**Issue by DreamingVisions** [tabalinas/jsgrid#491] opened 2016-10-21 19:43 UTC
So I've successfully implemented the plugin select2 into JsGrid to make use of its multiselect capabilities and I'm running into a little bit of a road block. I stole the prototype from one of your other jsfiddles, tabalinas, and adapted it to my uses, but when I try to use 2 "multiselect" custom fields as a filter, the items are being applied to both dropdowns. Here's a jsfiddle that might help:
[http://jsfiddle.net/5zxj2rf7/72/](url)

I'd like to think myself decent at javascript/jquery, but I feel like there might be something wrong here... or maybe  I'm just missing something. The only way I can work around this at the moment is declaring 2 prototypes that are exactly the same but with different names (ie. "multiselect" and "multiselect2".

Thanks!

**Comment by tonisostrat** [comment] 2016-10-21 19:46
Fiddle doesn't work.

We need to see how you're initializing and interacting with the Select2 fields. We have the same type of columns in our project and everything works fine.

**Comment by DreamingVisions** [comment] 2016-10-21 19:48
Oh sorry try this one [http://jsfiddle.net/5zxj2rf7/72/](url)

**Comment by tonisostrat** [comment] 2016-10-22 20:53
The cause of your problem: the `items` array you're declaring in your field is "global" in the context of your select fields - both of your columns inherit the array from their parent, `var MultiSelectField` instead of instantiating a separate object for themselves. So when you add countries first and then people, they get merged together.

There are two possible solutions:

1. Change the class you're extending from `Field` to `SelectField`.

```javascript
var MultiselectField = function(config) {
    jsGrid.SelectField.call(this, config);
};

MultiselectField.prototype = new jsGrid.SelectField({
  //configuration
});
```

2. Remove the `items` array from the field configuration 

```javascript
MultiselectField.prototype = new jsGrid.Field({
    
  items: [],
  //rest of your field conf
});
```

**Comment by DreamingVisions** [comment] 2016-10-24 15:46
I went with #1 and it works great. I'd like to think I'm fairly decent at this, but man i just looked right past that.

Thanks for the help!

**Closed** 2016-10-24 17:33 UTC
Labels: help wanted
