### ISSUE TITLE
'validate=required' doesn't work for number fields

### ISSUE THREAD

**Issue by snemarch** [tabalinas/jsgrid#309] opened 2016-06-09 13:22 UTC
When adding a new row, validate=required fails for number field. Blank fields get the value '0'.

Demo [here](https://jsfiddle.net/stmo5mtf/).

**Comment by kerro** [comment] 2016-06-09 22:10
If a field number isn't filled, the field value is set to 0 and passes the validation

return parseInt(this.insertControl.val() || 0, 10) in jsgrid.field.number.js

**Comment by tabalinas** [comment] 2016-06-30 23:26
I propose to consider this as a by design. The reason is that `number` field is defaulted to `0`. Thus I don't see any feasible fix w/o a breaking change. So if you want to validate `number` field, you need to use another validator `min`.
Of course, it should be specified in docs.

**Comment by tabalinas** [comment] 2016-07-02 11:56
Reopen the issue. If that one https://github.com/tabalinas/jsgrid/issues/125 will be fixed, we can fix this issue also.

**Closed** 2016-11-02 23:41 UTC
Labels: bug
