### ISSUE TITLE
How to export jsGrid Data in Excel

### ISSUE THREAD

**Issue by vikasrai0807** [tabalinas/jsgrid#704] opened 2017-03-29 10:39 UTC
How to export jsGrid Data in Excel

**Comment by richraid21** [comment] 2017-03-29 15:51
You cannot directly export to Excel. I currently have a pull request, #703 that would add CSV output functionality. This can be imported to excel.

**Comment by tabalinas** [comment] 2017-04-09 01:10
We can consider as a duplicate of https://github.com/tabalinas/jsgrid/issues/59

**Closed by tabalinas** 2017-04-09 01:10 UTC
Labels: duplicate, enhancement

**Comment by vijayvictory1** [comment] 2018-06-10 12:58
pls give me one example , jsGrid to Excel export
