### ISSUE TITLE
Cannot found 'jsgrid' module from entry file

### ISSUE THREAD

**Issue by aganglada** [tabalinas/jsgrid#160] opened 2015-12-05 17:21 UTC
Hello,

I'm trying to import jsgrid from my file but it cannot reach the final file/files.
In package.json you have defined main entry like this:

```
"main": [
     "dist/jsgrid.js",
     "dist/jsgrid.css",
     "dist/jsgrid-theme.css"
],
```

but any of this files exist in the jsgrid folder:

<img width="248" alt="screen shot 2015-12-05 at 18 19 30" src="https://cloud.githubusercontent.com/assets/922348/11609087/c3bd44ea-9b7c-11e5-9c60-e859e410baf3.png">

Is there anything I miss?

I'm importing with `import 'jsgrid';` ES2015 syntax

**Comment by tabalinas** [comment] 2015-12-05 19:03
You are right, npm package doesn't include `dist` directory due to `.gitignore`. It should be fixed (I'm going to add `.npmignore`).

Meanwhile, could you install jsGrid with bower?

```bash
$ bower install js-grid
```

Link to getting started: http://js-grid.com/getting-started/

**Closed** 2015-12-05 19:05 UTC
Labels: bug

**Comment by StefH** [comment] 2015-12-05 19:25
Is there also a nuget available?

**Comment by tabalinas** [comment] 2015-12-05 19:27
Good point. Created separate issue for that https://github.com/tabalinas/jsgrid/issues/161

**Comment by aganglada** [comment] 2015-12-06 16:10
When it's going to be a new release including this change?

**Comment by tabalinas** [comment] 2015-12-07 00:55
The minor release have been done yesterday. The next one is gonna be 2-4 weeks later. Installation with bower doesn't work for you?

**Comment by aganglada** [comment] 2015-12-07 11:01
Nop, I´m not using bower because I don´t like using both in my projects :(

**Comment by aganglada** [comment] 2015-12-07 11:59
Anyways bower also have the same main entry :(

**Comment by tabalinas** [comment] 2015-12-07 13:04
This is not an issie for bower, since dist is included in the release commit (the issue is only for npm package)

**Comment by aganglada** [comment] 2015-12-07 13:27
The problem I have is that I cannot release because we don't have bower in live server installed, so we only can work with npm packages and I cannot install bower just for one package.

Could you do a release with this changes?

**Comment by tabalinas** [comment] 2015-12-08 00:44
Ok, I'll prepare a minor release soon. Let you know in this ticket.

**Comment by tabalinas** [comment] 2015-12-09 19:50
New release v1.3.1 is ready. NPM works fine.

**Comment by aganglada** [comment] 2015-12-09 20:12
Thanks man!
