### ISSUE TITLE
Updating the row after updating/inserting with non editable/insertable field

### ISSUE THREAD

**Issue by mamisoa** [tabalinas/jsgrid#120] opened 2015-10-25 21:02 UTC
Hi,

I have a set of data with headers: ID, name, dob.
I get the data from a REST service.
I'm able to fetch the data with the controller LoadData.

```javascript
controller: {
             
             loadData: function() {
                var deferred = $.Deferred();
 
                $.ajax({
                    url: 'https://xxxxxxxxx/rest/patient',
                    dataType: 'json',
                    success: function(data){
                        deferred.resolve(data.content);
                    }
                }); 
                return deferred.promise();
            },
            
            insertItem: function(item) {
                console.log(item);
                var resp_j;
                $.ajax({
                    type: "POST",
                    url: "https://xxxxxx/rest/patient",
                    data: item,
                    dataType: "json",
                    success: function(data) {
                        var resp = eval(data);
                        var resp_j = JSON.stringify(resp.content)
                        console.log(resp_j);
                    }
                });
                return resp_j; // data;
```

Fields are configured as follows:

```javascript
fields: [
            { name: "id", type: "number", width: 50, title: "ID" , inserting: false, editing: false},
            { name: "name", type: "text", width: 50, title: "Name" },
            { name: "dob", type: "text", title: "DOB" },
            { type: "control" }
        ]
```

I'm not able, after insertion, to populate the new row with the resp_j JSON data, which contains the new inserted row (response from the rest server).

jsgrid just populate with the item data , which does not contain the id field, ignoring the "return resp_j"  -> the cell is left blank.

Mike

**Comment by tabalinas** [comment] 2015-10-25 23:14
Hi,

The problem is clear, you return an empty item, while promise that will be resolved with the result should be returned.

```js
insertItem: function(item) {
    var d = $.Deferred();

    $.ajax({
        type: "POST",
        url: "https://xxxxxx/rest/patient",
        data: item,
        dataType: "json",
        success: function(data) {
            var resp = eval(data);
            var resp_j = JSON.stringify(resp.content)
            d.resolve(resp_j);
        }
    });

    return d.promise();
}
```

**Closed** 2015-10-25 23:14 UTC
Labels: help wanted

**Comment by mamisoa** [comment] 2015-10-25 23:55
Thanks. Can you tell me what format the returned item should be? The rest server answers a JSON format like:
```javascript
{"content": [ "name": "Bou", "dob": "2001-01-02", "id": 55}]}
```
If I return this, it works:
```javascript
var test = {"name": "Bou", "dob": "2001-01-02", "id": 57};
return test;
```
but no matter what, if I try:

resp.content which gives: 
```javascript
 [{"name": "Bou", "dob": "2001-01-02", "id": 55}]}
```
or resp.content[0] which gives:
```javascript
{"name": "Bou", "dob": "2001-01-02", "id": 55}
```
I get an empty row... 

Mike

**Comment by tabalinas** [comment] 2015-10-25 23:58
An item json object should be returned. There should be no difference between hardcoded test item and item returned from the server. Be sure item json is correctly parsed (you can check it with console.log e.g.)
